# Generated by Django 5.0.1 on 2024-01-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user_login_datas',
            },
        ),
    ]
